### PR TITLE
[Fix] Fix bugs in guas1d config

### LINKED ISSUE #223: FileNotFoundError gaus1d.py
Hi, you made a small mistake on a filename.
It should be ```./mmhuman3d/configs/_base_/post_processing/gaus1d.py``` but not ```guas1d.py``` which may cause FileNotFoundError when setting ``` --smooth_type gaus1d```
Please check it.
And also it's wrong name in the ```getting_started.md``` at Inference part.

### PR DESCRIPTION
**Pull request by Fubuki901**
Resolves #223

### CODE REVIEW

**Review by juxuan27 — APPROVED** [review]
Approve. Everything seems fine!

**Comment by ttxskk** [comment]
Reopen this PR, please review it.

**Comment by juxuan27** [comment]
Hi, @Fubuki901! We just find out this PR is closed instead of merged by mistake, so we reopen it. However, we find another guas1d [here](https://github.com/open-mmlab/mmhuman3d/blob/a1a5269ddad43add3d1b268ccb4918bf36a90359/docs_zh-CN/getting_started.md) and we can not fix it directly in this PR for limits of authority. Could you please help us fix it? Thank you again for your contribution to MMHuman3D!

**Comment by Fubuki901** [comment]
@juxuan27 Added new commit.

**Comment by juxuan27** [comment]
Approve. Everything seems fine!

**Comment by OpenMMLab-Coordinator** [comment]
fubuki901，您好！您在MMHuman3D项目中给我们提的PR非常重要，感谢您付出私人时间帮助改进开源项目，相信很多开发者会从你的PR中受益。
我们非常期待与您继续合作，OpenMMLab专门成立了贡献者组织MMSIG，为贡献者们提供开源证书、荣誉体系和专享好礼，可通过添加微信：openmmlabwx 联系我们（请备注mmsig+GitHub id），由衷希望您能加入！


Hi @Fubuki901 ！First of all, we want to express our gratitude for your significant PR in the MMHuman3D project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
